I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script_wolf1.rpy", line 151, in script
    d "You died..."
Exception: Sayer 'd' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script_wolf1.rpy", line 151, in script
    d "You died..."
  File "C:\Users\demim\OneDrive\Documenten\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\demim\OneDrive\Documenten\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\demim\OneDrive\Documenten\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'd' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.6.25022803
White Tail 1.0
Tue Mar 18 13:21:57 2025
